apiVersion: v1
entries:
  mistokenly:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-12-02T06:19:52.5561786+10:00"
    description: A Helm chart for Mistokenly
    digest: 46bc4d982e329221ca0ff743f07fa34f8b494d431d67c4394463af8431d9de3e
    keywords:
    - pii
    - database
    - cache
    maintainers:
    - email: hello@plainfunction.com.au
      name: Ceejay Kelly
    name: mistokenly
    type: application
    urls:
    - https://plainfunction.github.io/mistokenly/deploy/charts/mistokenly-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-02T06:19:52.5551696+10:00"
