apiVersion: v2
name: mistokenly
description: A Helm chart for Mistokenly
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - pii
  - database
  - cache
maintainers:
  - name: Ceejay Kelly
    email: hello@plainfunction.com.au