{{- if not .Values.pii.kek.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kek-secret
type: Opaque
data:
  KEK_BASE64: {{ .Values.pii.kek.kekBase64 | b64enc }}
{{- end }}