{{- if .Values.postgres }}
{{- if .Values.postgres.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-persistent
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres-persistent
{{- end }}
{{- end }}