{{- if .Values.postgres }}
{{- if .Values.postgres.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-persistent
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres-persistent
{{- end }}
{{- end }}