apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-persistence
  labels:
    app: {{ .Release.Name }}-persistence
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-persistence
  ports:
  - name: grpc
    port: {{ .Values.persistence.service.port }}
    targetPort: 9082
    protocol: TCP