apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pii
  labels:
    app: {{ .Release.Name }}-pii
spec:
  type: {{ .Values.pii.service.type }}
  selector:
    app: {{ .Release.Name }}-pii
  ports:
  - name: grpc
    port: {{ .Values.pii.service.port }}
    targetPort: 9080
    protocol: TCP
  sessionAffinity: None